package com.pj.ssm.crm.settings.mapper;

import com.pj.ssm.crm.settings.domain.DicValue;

import java.util.List;

public interface DicValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Thu May 05 16:14:28 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Thu May 05 16:14:28 CST 2022
     */
    int insert(DicValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Thu May 05 16:14:28 CST 2022
     */
    int insertSelective(DicValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Thu May 05 16:14:28 CST 2022
     */
    DicValue selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Thu May 05 16:14:28 CST 2022
     */
    int updateByPrimaryKeySelective(DicValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Thu May 05 16:14:28 CST 2022
     */
    int updateByPrimaryKey(DicValue record);

    /**
     * 查询下拉列表字典值
     */
    List<DicValue> selectDicValueByTypeCode(String typeCode);

    /**
     * 为图表提供坐标轴字段
     */
    List<String> selectLegendByTypeCode(String typeCode);

    /**
     * 根据stageId查询stage名称
     */
    String selectStageNameByStageId(String stageId);
}