package com.pj.ssm.crm.settings.mapper;

import com.pj.ssm.crm.settings.domain.User;

import java.util.List;
import java.util.Map;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Thu Apr 21 16:48:31 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Thu Apr 21 16:48:31 CST 2022
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Thu Apr 21 16:48:31 CST 2022
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Thu Apr 21 16:48:31 CST 2022
     */
    User selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Thu Apr 21 16:48:31 CST 2022
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Thu Apr 21 16:48:31 CST 2022
     */
    int updateByPrimaryKey(User record);
    /**
     * 根据账号密码查询用户
     */
    User selectUserByLoginActAndPwd(Map<String, Object> map);

    /**
     * 查询所有用户信息
     */
    List<User> selectAllUsers();

    String selectIDByUserName(String userName);

    /**
     * 根据登录名和登录密码查找用户
     */
    User selectUserByUserNamePwd(Map<String, Object> map);

    int updateLoginPwdByLoginActNewPwd(Map<String, Object> map);
}